name: gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.1
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=2.0.0  # PyTorch 2.0.0+ is compatible with CUDA 12.1
  - torchaudio=2.0.0  # Matching version for PyTorch 2.0.0
  - torchvision=0.15.0  # Matching version for PyTorch 2.0.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn

